### ISSUE TITLE
Allow for launching Rubber from functions

### ISSUE THREAD

**Issue by GroovinChip** [mcrovero/rubber#1]
Being able to hide Rubber and make it appear and disappear via functions would be great

**Comment by mcrovero** [comment]
It is possible with the latest version.
Just call:
```dart
_controller.visibility = true; //false
```

**Comment by GroovinChip** [comment]
So in, say, the onPressed for a FAB:
```
onPressed: () {
   _controller.visibility = true;
}```

Is that right? Also, what would the proper values be to make Rubber mimic a ModalBottomSheet, where it appears at a set height and can be dismissed?

**Comment by mcrovero** [comment]
Exactly!
To make it mimic the ModalBottomSheet you can set the animationController as follows:
```dart
_controller = RubberAnimationController(
      vsync: this,
      lowerBound: 0.0,
      upperBound: 0.5,
      duration: Duration(milliseconds: 200)
);
```
and open it with
```dart
 _controller.launchTo(AnimationState.expanded);
```
I'm probably simplify this mechanism in the next release.

**Comment by GroovinChip** [comment]
Thank you, I'll try it out! Are you on twitter? Good place to announce releases

**Comment by GroovinChip** [comment]
ok, I just tried it out, and swiping up on Rubber doesn't make it expand. Swiping down, however, does dismiss Rubber with a very quick red screen error.

**Comment by mcrovero** [comment]
Yes, I've just fixed the red screen issue in the newest version. 
Swiping up shouldn't open the bottom sheet because it would prevent the lower layer from scrolling.

**Comment by mcrovero** [comment]
Yes, I'm on Twitter as @mattia_crovero.
Thanks for the advice!

**Comment by GroovinChip** [comment]
So it's not possible to use Rubber in this way at all? I've been on the
hunt for a way to replicate Google Maps's expanding bottom sheet for months
and haven't found anything.

**Comment by mcrovero** [comment]
In Google maps the swipe starts from the BottomNavigationView, I think that it is possible to reproduce it with rubber. It could be a nice feature for the library

**Comment by GroovinChip** [comment]
Looking forward to updates! I followed you on twitter. If you're able to replicate the Google Maps sheet, I will be in awe haha.
