### ISSUE TITLE
Got Assertion Error when scrolling the Upper layer of bottom sheet

### ISSUE THREAD

**Issue by ckarthickit** [mcrovero/rubber#16]
**Describe the bug**
When i was scrolling the bottom Sheet , i got the below exception

**To Reproduce**
1. Random Error

**Expected behavior**

**Screenshots**

> I/flutter (22346): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (22346): The following assertion was thrown while handling a gesture:
I/flutter (22346): 'package:rubber/src/bottom_sheet.dart': Failed assertion: line 158 pos 14: '_drag == null': is not
I/flutter (22346): true.
I/flutter (22346): 
I/flutter (22346): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22346): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22346): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22346):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (22346): 
I/flutter (22346): When the exception was thrown, this was the stack:
I/flutter (22346): #2      _RubberBottomSheetState._onVerticalDragDown (package:rubber/src/bottom_sheet.dart:158:14)
I/flutter (22346): #3      DragGestureRecognizer.addPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:123:46)
I/flutter (22346): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (22346): #5      DragGestureRecognizer.addPointer (package:flutter/src/gestures/monodrag.dart:123:9)
I/flutter (22346): #6      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:698:18)
I/flutter (22346): #7      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2519:14)
I/flutter (22346): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (22346): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (22346): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (22346): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (22346): #12     _invoke1 (dart:ui/hooks.dart:173:13)
I/flutter (22346): #13     _dispatchPointerDataPacket (dart:ui/hooks.dart:127:5)
I/flutter (22346): (elided 2 frames from class _AssertionError)
I/flutter (22346): 
I/flutter (22346): Handler: onDown
I/flutter (22346): Recognizer:
I/flutter (22346):   VerticalDragGestureRecognizer#30ccf(debugOwner: GestureDetector)
I/flutter (22346): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22346): Another exception was thrown: 'package:rubber/src/bottom_sheet.dart': Failed assertion: line 219 pos 14: '_drag == null': is not true.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 
 - Browser: NA
 - Version 0.2.6

**Additional context**

**Comment by CristianDRM** [comment]
I'm getting this error too

**Comment by DK15** [comment]
[This](https://github.com/mcrovero/rubber/pull/17) PR fixes above issue.

**Comment by srcho8** [comment]
i have similar problem

════════ Exception caught by gesture ═════════
══════════════════════════════════
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      RubberAnimationController.stop
package:rubber/src/animation_controller.dart:500
#1      RubberAnimationController.value=
package:rubber/src/animation_controller.dart:254
#2      RubberBottomSheetState._onVerticalDragUpdate
package:rubber/src/bottom_sheet.dart:261
#3      DragGestureRecognizer._checkUpdate.<anonymous closure>
package:flutter/…/gestures/monodrag.dart:436
#4      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
...
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#22e78
    debugOwner: GestureDetector
    start behavior: start
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════
