### ISSUE TITLE
How to ensure proper widget height when working with percentages?

### ISSUE THREAD

**Issue by mochar** [mcrovero/rubber#21]
When using a percentage to set the lowerBoundValue and the bottom sheet is collapsed, how can I make sure that the widget on the top of  the bottom sheet expands the area properly? This is for example and issue when I switch to landscape mode, as the available size is much smaller then, which is causing overflow issues. 

Thanks!!!

**Comment by mcrovero** [comment]
I think you should probably wrap your upperLayer with a Scrollable widget in order to avoid the overflow issues.
Provide your code if this doesn't fix it

**Comment by mochar** [comment]
I guess what I'm asking is how to make sure that the information shown in the "header" portion of the sheet fits perfectly in the visible area when collapsed. For example, in "tall" devices, a lower bound value of 10%  shows more than just the header widget, while in "shorter" devices the header might not be completely visible.

The obvious solution is setting the pixel value instead of percentage, but this currently leads to an error (see my other issue).

**Comment by mochar** [comment]
The new header and headerHeight property solved this. Thank you :-)
