### ISSUE TITLE
Shape customization

### ISSUE THREAD

**Issue by Salby** [mcrovero/rubber#22]
It would be really nice if you were able to change the shape of the sheet, for example to create rounded corners at the top of the sheet, like many of Google's redesigned apps have.

**Comment by mcrovero** [comment]
It isn't customizable through the RubberBottomSheet widget but you can directly change the shape of the layers.
A good UI example can be found [here](https://github.com/alexandr2levin/my_mikhailovka)

**Comment by Salby** [comment]
You're right I hadn't thought of that. My apologies.

**Comment by kelryazevedo** [comment]
@Salby , Hello, I saw this question about the shape and can you send me the link about some example when I can customize  corners?

**Comment by Salby** [comment]
I would make the sheet transparent, and define the background color and shape in the content of the sheet.
