### ISSUE TITLE
Variable to set an initial height value

### ISSUE THREAD

**Issue by icarus31** [mcrovero/rubber#3]
It will be nice to get a variable to set the initial height value of the widget. Something like:

```
RubberBottomSheet(
  lowerLayer: _getLowerLayer(),
  upperLayer: _getUpperLayer(),
  animationController: _controller,
  height: 100.0
),
```

If there is another way, I would like to know. Thanks and nice widget!

**Comment by mcrovero** [comment]
You can set the initial value from the [Animation Controller](https://github.com/mcrovero/rubber/wiki/Animation-controller)
The lower bound defines the initial position

**Comment by icarus31** [comment]
Thanks!
