### ISSUE TITLE
Getting current state of rubber

### ISSUE THREAD

**Issue by MahdiPishguy** [mcrovero/rubber#36]
how can i get state of this library when trigger collapsed, expanded?

**Comment by MahdiPishguy** [comment]
@guillaumeprevost did yo have this issue?

**Comment by yasfdany** [comment]
@MahdiPishguy you can get state from RubberAnimationController that is animationState.value, it will return AnimationState.expanded or AnimationState.collapsed

**Comment by MahdiPishguy** [comment]
@yasfdany  thanks, i have 

```dart
_controller = RubberAnimationController(
    vsync: this,
    lowerBoundValue: AnimationControllerValue(pixel: 0.0),
    springDescription: SpringDescription.withDampingRatio(
        mass: 1.5, stiffness: Stiffness.MEDIUM, 
        ratio: DampingRatio.HIGH_BOUNCY),
    duration: Duration(milliseconds: 100));
```

now how can i use your code?

i get warning for this below code

```dart
if (_controller.status == AnimationState.expanded) {
  print('aaa');
}
```

**Comment by yasfdany** [comment]
@MahdiPishguy you can use 

if (_controller.animationState.value == AnimationState.expanded) {
  print('aaa');
}

**Comment by MahdiPishguy** [comment]
@yasfdany thanks a lot, problem solved

**Comment by MahdiPishguy** [comment]
@yasfdany do you know how can i change height of rubber?

**Comment by MahdiPishguy** [comment]
@yasfdany do you know how can i change height of rubber?

> 
> 
> @MahdiPishguy you can use
> 
> if (_controller.animationState.value == AnimationState.expanded) {
> print('aaa');
> }

when i try to collapse rubber, it doesn't have any animation, do you know how can i resolve that?

**Comment by guillaumeprevost** [comment]
Hey, sorry I've missed out on this thread! I haven't experienced this. Hope you problem has been solved @MahdiPishguy !

**Comment by MahdiPishguy** [comment]
@guillaumeprevost thank you very much, yes, problem resolved :)
