### ISSUE TITLE
Value of type 'dart.core::int' can't be assigned to a variable of type 'dart.core::double'

### ISSUE THREAD

**Issue by cosminstoinescu** [mcrovero/rubber#6]
Please see the following error found in package:rubber/src/animation_controller.dart.

`'package:rubber/src/animation_controller.dart': error: line 355 pos 30:
file:///D:/Programing/FLUTTER/flutter/.pub-cache/hosted/pub.dartlang.org/rubber-0.2.5/lib/src/animation_controller.dart:355:30:

 Error: A value of type 'dart.core::int' can't be assigned to a variable of type 'dart.core::double'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.core::double'.
final double launchSpeed = 7;
                                             ^
final double launchSpeed = 7;
                                             ^`

**Comment by aryzhov** [comment]
This can be closed as Flutter 1.0 is using Dart 2.1 which handles the conversion from int to double automatically.
